fragment ImageFragment on FileField {
	id
	mimeType
	url
	title
	alt
	height
	width
	responsiveImage(imgixParams: { auto: format }, sizes: "(max-width: 46.24em) 100vw, 75vw") {
		src
		width
		height
		alt
		title
		base64
		sizes
	}
}
