fragment ImageRelatedFragment on FileField {
	id
	mimeType
	url
	title
	alt
	height
	width
	responsiveImage(
		imgixParams: { q: 70, ar: "8:5", fit: crop, auto: format }
		sizes: "(max-width: 46.24em) 25vw, 50vw"
	) {
		src
		width
		height
		alt
		title
		base64
		sizes
	}
}
