#import "./ImageFragment.gql"
#import "./VideoFragment.gql"

fragment ProgramFragmentLight on ProgramRecord {
	__typename
	_modelApiKey
	_publishedAt
	_createdAt
	id
	title
	startDate
	endDate
	intro(markdown: false)
	time
	image {
		...ImageThumbnailFragment
	}
	slug
}
