#import "./ImageFragment.gql"
#import "./VideoFragment.gql"

fragment ProgramFragment on ProgramRecord {
	__typename
	_modelApiKey
	_publishedAt
	_createdAt
	id
	title
	startDate
	endDate
	time
	address
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	misc

	partipants {
		...ParticipantFragmentLight
	}
	partner {
		...PartnerFragmentLight
	}

	slug
	externalLink
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}

							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}
