query AllAbouts($first: IntType = 500, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		...AboutFragmentLight
	}
	_allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

query MainAbout {
	allAbouts(first: 1) {
		...AboutFragment
	}
}

query AllAboutsMenu {
	allAbouts(first: 100) {
		_createdAt
		title
		slug
	}
}

fragment AboutFragment on AboutRecord {
	__typename
	_modelApiKey
	_createdAt
	id
	title
	intro
	slug
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							__typename
							... on AboutRecord {
								id
								slug
								title
							}
							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment AboutFragmentLight on AboutRecord {
	__typename
	_createdAt
	id
	title
	intro
	slug
	image {
		...ImageThumbnailFragment
	}
}
