query Contact {
	contact {
		id
		image {
			...ImageFragment
		}
		intro(markdown: false)
		slug
		title
		content {
			value
			blocks {
				__typename
				... on ImageRecord {
					__typename
					id
					layout
					image {
						...ImageFragment
					}
				}
				... on ImageGalleryRecord {
					__typename
					id
					images {
						...ImageThumbnailFragment
					}
				}
				... on LinkButtonRecord {
					__typename
					id
					link {
						__typename
						... on ExternalLinkRecord {
							__typename
							id
							title
							url
						}
						... on InternalLinkRecord {
							__typename
							id
							record {
								... on AboutRecord {
									__typename
									id
									slug
									title
								}
								... on LocationRecord {
									__typename
									id
									slug
									title
								}
								... on NewsRecord {
									__typename
									id
									slug
									title
								}
								... on ParticipantRecord {
									__typename
									id
									slug
									name
								}
								... on ProgramRecord {
									__typename
									id
									slug
									title
								}
							}
						}
					}
				}
				... on VideoRecord {
					__typename
					id
					title
					video {
						height
						width
						title
						provider
						providerUid
						thumbnailUrl
						url
					}
				}
				... on RecordInterface {
					__typename
					id
				}
			}
		}

		_seoMetaTags {
			attributes
			content
			tag
		}
	}
}
