query AllLearnMore($first: IntType = 500, $skip: IntType = 0) {
	allLearnMores(first: $first, skip: $skip, orderBy: [_createdAt_DESC]) {
		...LearnMoreFragment
	}
	_allLearnMoresMeta {
		count
	}
}

query AllLearnMoreCategories($first: IntType = 500, $skip: IntType = 0) {
	allLearnMoreCategories(first: $first, skip: $skip, orderBy: [_createdAt_DESC]) {
		id
		title
	}
	_allLearnMoreCategoriesMeta {
		count
	}
}

query LearnMore($slug: String!) {
	learnMore(filter: { slug: { eq: $slug } }) {
		...LearnMoreFragment
	}
}

fragment LearnMoreFragment on LearnMoreRecord {
	_createdAt
	id
	name
	intro(markdown: false)
	slug
	image {
		...ImageFragment
	}
	learnMoreCategory {
		id
		title
	}
	content {
		links
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on SoundRecord {
				id
				data
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
		}
	}
}
