query AllLocations($first: IntType = 100, $skip: IntType = 0, $yearId: ItemId) {
	locations: allLocations(
		filter: { year: { eq: $yearId } }
		first: $first
		skip: $skip
		orderBy: [_createdAt_DESC]
	) {
		...LocationFragmentLight
	}

	pagination: _allLocationsMeta {
		count
	}
}

query Location($slug: String!) {
	location(filter: { slug: { eq: $slug } }) {
		...LocationFragment
	}
}
