query Menu {
	abouts: allAbouts(first: 100) {
		id
		title
		slug
	}
	aboutMeta: _allAboutsMeta {
		count
	}
	programMeta: _allProgramsMeta {
		count
	}
	participantsMeta: _allParticipantsMeta {
		count
	}
	partnersMeta: _allPartnersMeta {
		count
	}

	general {
		whatSmi
		whatSv
		newsSv
		newsSmi
		contactSv
		contactSmi
		aboutSv
		aboutSmi
	}
}
