query Menu {
	allAbouts(first: 100) {
		id
		title
		slug
	}
	_allAboutsMeta {
		count
	}
	_allProgramsMeta {
		count
	}
	_allParticipantsMeta {
		count
	}
	_allPartnersMeta {
		count
	}
	general {
		...GeneralFragment
	}
}
