query AllPartners {
	allPartners(first: 100) {
		...PartnerFragmentLight
	}
	_allPartnersMeta {
		count
	}
}

query Partner($slug: String!) {
	partner(filter: { slug: { eq: $slug } }) {
		...PartnerFragment
	}
}

fragment PartnerFragment on PartnerRecord {
	_createdAt
	_publishedAt
	__typename
	id
	title
	intro(markdown: false)
	slug
	image {
		...ImageFragment
	}
	address
	city
	webpage
	_allReferencingPrograms(first: 100) {
		...ProgramFragmentLight
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}

							... on LocationRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment PartnerFragmentLight on PartnerRecord {
	id
	title
	intro(markdown: false)
	city
	image {
		...ImageThumbnailFragment
	}
	slug
	__typename
	_createdAt
	_publishedAt
	_firstPublishedAt
}
