query AllPrograms($first: IntType = 500, $skip: IntType = 0) {
	allPrograms(first: $first, skip: $skip, orderBy: [_firstPublishedAt_DESC]) {
		...ProgramFragmentLight
	}
	_allProgramsMeta {
		count
	}
}

fragment ProgramFragment on ProgramRecord {
	__typename
	_modelApiKey
	_publishedAt
	_createdAt
	id
	title
	startDate
	endDate
	time
	address
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	misc
	partipants {
		...ParticipantFragmentLight
	}
	partner {
		...PartnerFragmentLight
	}
	slug
	externalLink
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								__typename
								id
								slug
								title
							}

							... on LocationRecord {
								__typename
								id
								slug
								title
							}
							... on NewsRecord {
								__typename
								id
								slug
								title
							}
							... on ParticipantRecord {
								__typename
								id
								slug
								title
							}
							... on ProgramRecord {
								__typename
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment ProgramFragmentLight on ProgramRecord {
	__typename
	_modelApiKey
	_publishedAt
	_firstPublishedAt
	_createdAt
	id
	title
	startDate
	endDate
	intro(markdown: false)
	time
	image {
		...ImageThumbnailFragment
	}
	slug
}
