query Start {
	start {
		id
		content {
			__typename
			... on StartFullscreenVideoRecord {
				__typename
				id
				headline
				text(markdown: false)
				video {
					...VideoFragment
				}
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						internalTitle: title
						record {
							... on AboutRecord {
								id
								slug
								title
							}

							... on NewsRecord {
								id
								slug
								title
							}
							... on ParticipantRecord {
								id
								slug
								name
							}
							... on ProgramRecord {
								id
								slug
								title
							}
						}
					}
				}
			}

			
	}
}

query StartData($newsItems: IntType, $programItems: IntType, $date: Date) {
	news: allNews(first: $newsItems, orderBy: _createdAt_DESC) {
		...NewsFragmentLight
	}
	programs: allPrograms(
		filter: { startDate: { gte: $date } }

		first: $programItems
		orderBy: startDate_DESC
	) {
		...ProgramFragmentLight
	}
	participants: allParticipants(first: 100, orderBy: _createdAt_DESC) {
		...ParticipantFragmentLight
	}
}
