query Start {
	start {
		id
		content {
			__typename
			... on StartVideoRecord {
				__typename
				id
				title
				video {
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on StartFullscreenVideoRecord {
				__typename
				id
				text(markdown: false)
				newsText
				newsLink
				video {
					...VideoFragment
				}
			}
		}
	}
}

query StartData($newsItems: IntType, $programItems: IntType, $date: Date) {
	allNews(first: $newsItems, orderBy: _createdAt_DESC) {
		...NewsFragmentLight
	}
	allPrograms(
		filter: { startDate: { gte: $date } }

		first: $programItems
		orderBy: startDate_DESC
	) {
		...ProgramFragmentLight
	}
	allParticipants(first: 100, orderBy: _createdAt_DESC) {
		...ParticipantFragmentLight
	}
}
