query WhatWeDo($slug: String) {
	program(filter: { slug: { eq: $slug } }) {
		...ProgramFragment
	}
	participant(filter: { slug: { eq: $slug } }) {
		...ParticipantFragment
	}
	partner(filter: { slug: { eq: $slug } }) {
		...PartnerFragment
	}
}
